# Generated by Django 2.2.2 on 2019-06-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('cp', models.IntegerField()),
                ('tel', models.IntegerField()),
                ('type', models.TextField()),
                ('chambres', models.IntegerField()),
                ('position', models.CharField(max_length=255)),
                ('src_image', models.CharField(max_length=255)),
                ('equipements', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('prix', models.IntegerField()),
            ],
            options={
                'verbose_name': 'logement',
                'ordering': ['titre'],
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
