# Generated by Django 2.2.2 on 2019-06-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0002_auto_20190607_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('id_utilisateur', models.IntegerField()),
                ('id_logement', models.IntegerField()),
            ],
            options={
                'verbose_name': 'message',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=255)),
                ('mdp', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'utilisateur',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='logement',
            options={'ordering': ['id'], 'verbose_name': 'logement'},
        ),
        migrations.RenameField(
            model_name='logement',
            old_name='titre',
            new_name='intitule',
        ),
    ]
