# Generated by Django 2.2.2 on 2019-06-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0003_auto_20190607_1502'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
